apiVersion: v1
kind: Service
metadata:
  name: {{ template "app.name" . }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.headless }}
  clusterIP: None
  {{- end }}
  ports:
  {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ default .port .targetPort  }}
      protocol: {{ default "TCP" .protocol }}
  {{- end }}
  selector: {{ include "app.labels" . | nindent 4 }}
