app:
  name: sample-app
  component: backend
  branch: master
  env: dev

replicasCount: 1
# strategy:
#   type: Recreate

image:
  repository: chromko/sample-app
  tag: latest

service:
  headless: true
  ports:
    - name: http
      port: 8086

mysql:
  enabled: true
  mysqlDatabase: test
  mysqlUser: sa
  mysqlPassword: password

ingress:
  domain: localhost
  http:
    path: /start
    name: http
    tls:
      enabled: false
