---
# Source: sample-app/charts/mysql/templates/secrets.yaml

apiVersion: v1
kind: Secret
metadata:
  name: sample-mysql
  namespace: default
  labels:
    app: sample-mysql
    chart: "mysql-1.3.0"
    release: "sample"
    heritage: "Tiller"
type: Opaque
data:
  
  mysql-root-password: "b1JrMnZGRmJOcA=="
  
  
  mysql-password: "YlVGdkNYOUFWQw=="
  
---
# Source: sample-app/charts/mysql/templates/tests/test-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-mysql-test
  namespace: default
  labels:
    app: sample-mysql
    chart: "mysql-1.3.0"
    heritage: "Tiller"
    release: "sample"
data:
  run.sh: |-


---
# Source: sample-app/charts/mysql/templates/pvc.yaml

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sample-mysql
  namespace: default
  labels:
    app: sample-mysql
    chart: "mysql-1.3.0"
    release: "sample"
    heritage: "Tiller"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "8Gi"

---
# Source: sample-app/charts/mysql/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: sample-mysql
  namespace: default
  labels:
    app: sample-mysql
    chart: "mysql-1.3.0"
    release: "sample"
    heritage: "Tiller"
  annotations:
spec:
  type: ClusterIP
  ports:
  - name: mysql
    port: 3306
    targetPort: mysql
  selector:
    app: sample-mysql

---
# Source: sample-app/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: sample
  namespace: default
  labels: 
    app: sample
    env: dev
    component: backend
    version: latest
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: 8086
      targetPort: 8086
      protocol: TCP
  selector: 
    app: sample
    env: dev
    component: backend
    version: latest

---
# Source: sample-app/charts/mysql/templates/tests/test.yaml
apiVersion: v1
kind: Pod
metadata:
  name: sample-mysql-test
  namespace: default
  labels:
    app: sample-mysql
    chart: "mysql-1.3.0"
    heritage: "Tiller"
    release: "sample"
  annotations:
    "helm.sh/hook": test-success
spec:
  initContainers:
    - name: test-framework
      image: "dduportal/bats:0.4.0"
      command:
      - "bash"
      - "-c"
      - |
        set -ex
        # copy bats to tools dir
        cp -R /usr/local/libexec/ /tools/bats/
      volumeMounts:
      - mountPath: /tools
        name: tools
  containers:
    - name: sample-test
      image: "mysql:5.7.14"
      command: ["/tools/bats/bats", "-t", "/tests/run.sh"]
      volumeMounts:
      - mountPath: /tests
        name: tests
        readOnly: true
      - mountPath: /tools
        name: tools
  volumes:
  - name: tests
    configMap:
      name: sample-mysql-test
  - name: tools
    emptyDir: {}
  restartPolicy: Never

---
# Source: sample-app/charts/mysql/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sample-mysql
  namespace: default
  labels:
    app: sample-mysql
    chart: "mysql-1.3.0"
    release: "sample"
    heritage: "Tiller"

spec:
  template:
    metadata:
      labels:
        app: sample-mysql
    spec:
      initContainers:
      - name: "remove-lost-found"
        image: "busybox:1.29.3"
        imagePullPolicy: "IfNotPresent"
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
          
        command:  ["rm", "-fr", "/var/lib/mysql/lost+found"]
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
      # - name: do-something
      #   image: busybox
      #   command: ['do', 'something']
      
      containers:
      - name: sample-mysql
        image: "mysql:5.7.14"
        imagePullPolicy: "IfNotPresent"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sample-mysql
              key: mysql-root-password
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sample-mysql
              key: mysql-password
              optional: true
        - name: MYSQL_USER
          value: ""
        - name: MYSQL_DATABASE
          value: ""
        ports:
        - name: mysql
          containerPort: 3306
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}"
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
        # - name: extras
        #   mountPath: /usr/share/extras
        #   readOnly: true
        
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: sample-mysql
      # - name: extras
      #   emptyDir: {}
      

---
# Source: sample-app/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample
  namespace: default
  labels: 
    app: sample
    env: dev
    component: backend
    version: latest
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels: 
      app: sample
      env: dev
      component: backend
      version: latest
  template:
    metadata:
      labels: 
        app: sample
        env: dev
        component: backend
        version: latest
    spec:
      initContainers:
      containers:
      - name: "backend"
        image: "chromko/sample-app:latest"
        ports:
          - name: http
            containerPort: 8086
        imagePullPolicy: Always
        env:
          - name: CONFIG_PATH
            value: /etc/secrets/config

---
# Source: sample-app/templates/ingress-http.yaml
---apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sample-http
  namespace: default
  labels: 
    app: sample
    env: dev
    component: backend
    version: latest
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/proxy-body-size: 50m
    kubernetes.io/ingress.allow-http: "false"
    nginx.ingress.kubernetes.io/client-body-buffer-size: 50m
    nginx.ingress.kubernetes.io/client-max-body-size: 50m
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: 90s
    nginx.ingress.kubernetes.io/proxy-read-timeout: 90s
    
spec:
  rules:
    - host: sample-sample-app.localhost
      http:
        paths:
          - path: /start
            backend:
              serviceName: sample
              servicePort: http

    - host: sample-sample-app.localhost
      http:
        paths:
          - path: /start
            backend:
              serviceName: sample
              servicePort: http
---
# Source: sample-app/charts/mysql/templates/configurationFiles-configmap.yaml

---
# Source: sample-app/charts/mysql/templates/initializationFiles-configmap.yaml

---
# Source: sample-app/charts/mysql/templates/servicemonitor.yaml


